apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ template "harbor.jobservice" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: jobservice
