apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ template "harbor.registry" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - name: registry
      port: 5000
    - name: controller
      port: 8080
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: registry
